version: "3.8"

services:
    ui:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ui
        ports:
            - "3000:80"
        depends_on:
            api-gateway:
                condition: service_started
        networks:
            - ecommerce-network

    api-gateway:
        image: ecommerce-microservices-api-gateway:latest
        container_name: api-gateway
        ports:
            - "8000:8000"
        environment:
            - PORT=8000
            - JWT_SECRET=${JWT_SECRET}
            - SERVICE_SECRET=${SERVICE_SECRET}
            - JWT_EXPIRES_IN=24h
            - USER_SERVICE_URL=http://user-service:8081
            - PRODUCT_SERVICE_URL=http://product-service:8082
            - ORDER_SERVICE_URL=http://order-service:8083
            - PAYMENT_SERVICE_URL=http://payment-service:8084
            - NOTIFICATION_SERVICE_URL=http://notification-service:8085
            - RATE_LIMIT_WINDOW_MS=900000
            - RATE_LIMIT_MAX=100
        networks:
            - ecommerce-network

networks:
    ecommerce-network:
        driver: bridge
