apiVersion: apps/v1
kind: Deployment
metadata:
    name: ui
    namespace: ecommerce
    labels:
        app: ui
        component: frontend
    annotations:
        description: "UI Application Deployment"
        version: "1.0"
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    selector:
        matchLabels:
            app: ui
    template:
        metadata:
            labels:
                app: ui
                component: frontend
            annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "80"
        spec:
            securityContext:
                runAsNonRoot: true
                runAsUser: 101
                runAsGroup: 101
                fsGroup: 101
            containers:
                - name: ui
                  image: ui:1.0
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 80
                  env:
                      - name: VITE_API_URL
                        value: "http://api-gateway:8000/api"
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "100m"
                      limits:
                          memory: "256Mi"
                          cpu: "200m"
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: 80
                      initialDelaySeconds: 30
                      periodSeconds: 10
                  readinessProbe:
                      httpGet:
                          path: /health
                          port: 80
                      initialDelaySeconds: 5
                      periodSeconds: 5
                  startupProbe:
                      httpGet:
                          path: /health
                          port: 80
                      initialDelaySeconds: 10
                      periodSeconds: 5
                  securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                          drop:
                              - ALL
                      readOnlyRootFilesystem: true
            affinity:
                podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                        - weight: 100
                          podAffinityTerm:
                              labelSelector:
                                  matchExpressions:
                                      - key: app
                                        operator: In
                                        values:
                                            - ui
                              topologyKey: kubernetes.io/hostname
